# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home-local/student/SpaceShooter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home-local/student/SpaceShooter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"libassimp3.0-r1270-OGLtuts\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest3 --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home-local/student/SpaceShooter/CMakeFiles /home-local/student/SpaceShooter/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home-local/student/SpaceShooter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named andrei_libs

# Build rule for target.
andrei_libs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 andrei_libs
.PHONY : andrei_libs

# fast build rule for target.
andrei_libs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/andrei_libs.dir/build.make CMakeFiles/andrei_libs.dir/build
.PHONY : andrei_libs/fast

#=============================================================================
# Target rules for targets named serg_libs

# Build rule for target.
serg_libs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 serg_libs
.PHONY : serg_libs

# fast build rule for target.
serg_libs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serg_libs.dir/build.make CMakeFiles/serg_libs.dir/build
.PHONY : serg_libs/fast

#=============================================================================
# Target rules for targets named game_core

# Build rule for target.
game_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game_core
.PHONY : game_core

# fast build rule for target.
game_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_core.dir/build.make CMakeFiles/game_core.dir/build
.PHONY : game_core/fast

#=============================================================================
# Target rules for targets named render_engine

# Build rule for target.
render_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 render_engine
.PHONY : render_engine

# fast build rule for target.
render_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/build
.PHONY : render_engine/fast

#=============================================================================
# Target rules for targets named OBJLoader

# Build rule for target.
OBJLoader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OBJLoader
.PHONY : OBJLoader

# fast build rule for target.
OBJLoader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBJLoader.dir/build.make CMakeFiles/OBJLoader.dir/build
.PHONY : OBJLoader/fast

#=============================================================================
# Target rules for targets named mymatrix

# Build rule for target.
mymatrix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mymatrix
.PHONY : mymatrix

# fast build rule for target.
mymatrix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymatrix.dir/build.make CMakeFiles/mymatrix.dir/build
.PHONY : mymatrix/fast

#=============================================================================
# Target rules for targets named mydict

# Build rule for target.
mydict: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mydict
.PHONY : mydict

# fast build rule for target.
mydict/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mydict.dir/build.make CMakeFiles/mydict.dir/build
.PHONY : mydict/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named mycontrol

# Build rule for target.
mycontrol: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mycontrol
.PHONY : mycontrol

# fast build rule for target.
mycontrol/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mycontrol.dir/build.make CMakeFiles/mycontrol.dir/build
.PHONY : mycontrol/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named render

# Build rule for target.
render: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 render
.PHONY : render

# fast build rule for target.
render/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/build
.PHONY : render/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named mynum

# Build rule for target.
mynum: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mynum
.PHONY : mynum

# fast build rule for target.
mynum/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mynum.dir/build.make CMakeFiles/mynum.dir/build
.PHONY : mynum/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ANTTWEAKBAR_116_OGLCORE_GLFW

# Build rule for target.
ANTTWEAKBAR_116_OGLCORE_GLFW: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ANTTWEAKBAR_116_OGLCORE_GLFW
.PHONY : ANTTWEAKBAR_116_OGLCORE_GLFW

# fast build rule for target.
ANTTWEAKBAR_116_OGLCORE_GLFW/fast:
	$(MAKE) $(MAKESILENT) -f external/CMakeFiles/ANTTWEAKBAR_116_OGLCORE_GLFW.dir/build.make external/CMakeFiles/ANTTWEAKBAR_116_OGLCORE_GLFW.dir/build
.PHONY : ANTTWEAKBAR_116_OGLCORE_GLFW/fast

#=============================================================================
# Target rules for targets named GLEW_1130

# Build rule for target.
GLEW_1130: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GLEW_1130
.PHONY : GLEW_1130

# fast build rule for target.
GLEW_1130/fast:
	$(MAKE) $(MAKESILENT) -f external/CMakeFiles/GLEW_1130.dir/build.make external/CMakeFiles/GLEW_1130.dir/build
.PHONY : GLEW_1130/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f external/glfw-3.1.2/CMakeFiles/uninstall.dir/build.make external/glfw-3.1.2/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f external/glfw-3.1.2/src/CMakeFiles/glfw.dir/build.make external/glfw-3.1.2/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) $(MAKESILENT) -f external/assimp-3.0.1270/contrib/zlib/CMakeFiles/zlib.dir/build.make external/assimp-3.0.1270/contrib/zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) $(MAKESILENT) -f external/assimp-3.0.1270/code/CMakeFiles/assimp.dir/build.make external/assimp-3.0.1270/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named BulletSoftBody

# Build rule for target.
BulletSoftBody: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BulletSoftBody
.PHONY : BulletSoftBody

# fast build rule for target.
BulletSoftBody/fast:
	$(MAKE) $(MAKESILENT) -f external/bullet-2.81-rev2613/src/BulletSoftBody/CMakeFiles/BulletSoftBody.dir/build.make external/bullet-2.81-rev2613/src/BulletSoftBody/CMakeFiles/BulletSoftBody.dir/build
.PHONY : BulletSoftBody/fast

#=============================================================================
# Target rules for targets named BulletCollision

# Build rule for target.
BulletCollision: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BulletCollision
.PHONY : BulletCollision

# fast build rule for target.
BulletCollision/fast:
	$(MAKE) $(MAKESILENT) -f external/bullet-2.81-rev2613/src/BulletCollision/CMakeFiles/BulletCollision.dir/build.make external/bullet-2.81-rev2613/src/BulletCollision/CMakeFiles/BulletCollision.dir/build
.PHONY : BulletCollision/fast

#=============================================================================
# Target rules for targets named BulletDynamics

# Build rule for target.
BulletDynamics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BulletDynamics
.PHONY : BulletDynamics

# fast build rule for target.
BulletDynamics/fast:
	$(MAKE) $(MAKESILENT) -f external/bullet-2.81-rev2613/src/BulletDynamics/CMakeFiles/BulletDynamics.dir/build.make external/bullet-2.81-rev2613/src/BulletDynamics/CMakeFiles/BulletDynamics.dir/build
.PHONY : BulletDynamics/fast

#=============================================================================
# Target rules for targets named LinearMath

# Build rule for target.
LinearMath: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LinearMath
.PHONY : LinearMath

# fast build rule for target.
LinearMath/fast:
	$(MAKE) $(MAKESILENT) -f external/bullet-2.81-rev2613/src/LinearMath/CMakeFiles/LinearMath.dir/build.make external/bullet-2.81-rev2613/src/LinearMath/CMakeFiles/LinearMath.dir/build
.PHONY : LinearMath/fast

common/controls.o: common/controls.cpp.o

.PHONY : common/controls.o

# target to build an object file
common/controls.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/controls.cpp.o
.PHONY : common/controls.cpp.o

common/controls.i: common/controls.cpp.i

.PHONY : common/controls.i

# target to preprocess a source file
common/controls.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/controls.cpp.i
.PHONY : common/controls.cpp.i

common/controls.s: common/controls.cpp.s

.PHONY : common/controls.s

# target to generate assembly for a file
common/controls.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/controls.cpp.s
.PHONY : common/controls.cpp.s

common/quaternion_utils.o: common/quaternion_utils.cpp.o

.PHONY : common/quaternion_utils.o

# target to build an object file
common/quaternion_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/quaternion_utils.cpp.o
.PHONY : common/quaternion_utils.cpp.o

common/quaternion_utils.i: common/quaternion_utils.cpp.i

.PHONY : common/quaternion_utils.i

# target to preprocess a source file
common/quaternion_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/quaternion_utils.cpp.i
.PHONY : common/quaternion_utils.cpp.i

common/quaternion_utils.s: common/quaternion_utils.cpp.s

.PHONY : common/quaternion_utils.s

# target to generate assembly for a file
common/quaternion_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/quaternion_utils.cpp.s
.PHONY : common/quaternion_utils.cpp.s

common/shader.o: common/shader.cpp.o

.PHONY : common/shader.o

# target to build an object file
common/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/shader.cpp.o
.PHONY : common/shader.cpp.o

common/shader.i: common/shader.cpp.i

.PHONY : common/shader.i

# target to preprocess a source file
common/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/shader.cpp.i
.PHONY : common/shader.cpp.i

common/shader.s: common/shader.cpp.s

.PHONY : common/shader.s

# target to generate assembly for a file
common/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/shader.cpp.s
.PHONY : common/shader.cpp.s

common/texture.o: common/texture.cpp.o

.PHONY : common/texture.o

# target to build an object file
common/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/texture.cpp.o
.PHONY : common/texture.cpp.o

common/texture.i: common/texture.cpp.i

.PHONY : common/texture.i

# target to preprocess a source file
common/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/texture.cpp.i
.PHONY : common/texture.cpp.i

common/texture.s: common/texture.cpp.s

.PHONY : common/texture.s

# target to generate assembly for a file
common/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/texture.cpp.s
.PHONY : common/texture.cpp.s

common/vboindexer.o: common/vboindexer.cpp.o

.PHONY : common/vboindexer.o

# target to build an object file
common/vboindexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/vboindexer.cpp.o
.PHONY : common/vboindexer.cpp.o

common/vboindexer.i: common/vboindexer.cpp.i

.PHONY : common/vboindexer.i

# target to preprocess a source file
common/vboindexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/vboindexer.cpp.i
.PHONY : common/vboindexer.cpp.i

common/vboindexer.s: common/vboindexer.cpp.s

.PHONY : common/vboindexer.s

# target to generate assembly for a file
common/vboindexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/common/vboindexer.cpp.s
.PHONY : common/vboindexer.cpp.s

src/addlibs/MyControl.o: src/addlibs/MyControl.cpp.o

.PHONY : src/addlibs/MyControl.o

# target to build an object file
src/addlibs/MyControl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mycontrol.dir/build.make CMakeFiles/mycontrol.dir/src/addlibs/MyControl.cpp.o
.PHONY : src/addlibs/MyControl.cpp.o

src/addlibs/MyControl.i: src/addlibs/MyControl.cpp.i

.PHONY : src/addlibs/MyControl.i

# target to preprocess a source file
src/addlibs/MyControl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mycontrol.dir/build.make CMakeFiles/mycontrol.dir/src/addlibs/MyControl.cpp.i
.PHONY : src/addlibs/MyControl.cpp.i

src/addlibs/MyControl.s: src/addlibs/MyControl.cpp.s

.PHONY : src/addlibs/MyControl.s

# target to generate assembly for a file
src/addlibs/MyControl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mycontrol.dir/build.make CMakeFiles/mycontrol.dir/src/addlibs/MyControl.cpp.s
.PHONY : src/addlibs/MyControl.cpp.s

src/addlibs/MyDict.o: src/addlibs/MyDict.cpp.o

.PHONY : src/addlibs/MyDict.o

# target to build an object file
src/addlibs/MyDict.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mydict.dir/build.make CMakeFiles/mydict.dir/src/addlibs/MyDict.cpp.o
.PHONY : src/addlibs/MyDict.cpp.o

src/addlibs/MyDict.i: src/addlibs/MyDict.cpp.i

.PHONY : src/addlibs/MyDict.i

# target to preprocess a source file
src/addlibs/MyDict.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mydict.dir/build.make CMakeFiles/mydict.dir/src/addlibs/MyDict.cpp.i
.PHONY : src/addlibs/MyDict.cpp.i

src/addlibs/MyDict.s: src/addlibs/MyDict.cpp.s

.PHONY : src/addlibs/MyDict.s

# target to generate assembly for a file
src/addlibs/MyDict.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mydict.dir/build.make CMakeFiles/mydict.dir/src/addlibs/MyDict.cpp.s
.PHONY : src/addlibs/MyDict.cpp.s

src/addlibs/MyNum.o: src/addlibs/MyNum.cpp.o

.PHONY : src/addlibs/MyNum.o

# target to build an object file
src/addlibs/MyNum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mynum.dir/build.make CMakeFiles/mynum.dir/src/addlibs/MyNum.cpp.o
.PHONY : src/addlibs/MyNum.cpp.o

src/addlibs/MyNum.i: src/addlibs/MyNum.cpp.i

.PHONY : src/addlibs/MyNum.i

# target to preprocess a source file
src/addlibs/MyNum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mynum.dir/build.make CMakeFiles/mynum.dir/src/addlibs/MyNum.cpp.i
.PHONY : src/addlibs/MyNum.cpp.i

src/addlibs/MyNum.s: src/addlibs/MyNum.cpp.s

.PHONY : src/addlibs/MyNum.s

# target to generate assembly for a file
src/addlibs/MyNum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mynum.dir/build.make CMakeFiles/mynum.dir/src/addlibs/MyNum.cpp.s
.PHONY : src/addlibs/MyNum.cpp.s

src/addlibs/matrix.o: src/addlibs/matrix.cpp.o

.PHONY : src/addlibs/matrix.o

# target to build an object file
src/addlibs/matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymatrix.dir/build.make CMakeFiles/mymatrix.dir/src/addlibs/matrix.cpp.o
.PHONY : src/addlibs/matrix.cpp.o

src/addlibs/matrix.i: src/addlibs/matrix.cpp.i

.PHONY : src/addlibs/matrix.i

# target to preprocess a source file
src/addlibs/matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymatrix.dir/build.make CMakeFiles/mymatrix.dir/src/addlibs/matrix.cpp.i
.PHONY : src/addlibs/matrix.cpp.i

src/addlibs/matrix.s: src/addlibs/matrix.cpp.s

.PHONY : src/addlibs/matrix.s

# target to generate assembly for a file
src/addlibs/matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mymatrix.dir/build.make CMakeFiles/mymatrix.dir/src/addlibs/matrix.cpp.s
.PHONY : src/addlibs/matrix.cpp.s

src/andrei/andrei_main.o: src/andrei/andrei_main.cpp.o

.PHONY : src/andrei/andrei_main.o

# target to build an object file
src/andrei/andrei_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/andrei_libs.dir/build.make CMakeFiles/andrei_libs.dir/src/andrei/andrei_main.cpp.o
.PHONY : src/andrei/andrei_main.cpp.o

src/andrei/andrei_main.i: src/andrei/andrei_main.cpp.i

.PHONY : src/andrei/andrei_main.i

# target to preprocess a source file
src/andrei/andrei_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/andrei_libs.dir/build.make CMakeFiles/andrei_libs.dir/src/andrei/andrei_main.cpp.i
.PHONY : src/andrei/andrei_main.cpp.i

src/andrei/andrei_main.s: src/andrei/andrei_main.cpp.s

.PHONY : src/andrei/andrei_main.s

# target to generate assembly for a file
src/andrei/andrei_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/andrei_libs.dir/build.make CMakeFiles/andrei_libs.dir/src/andrei/andrei_main.cpp.s
.PHONY : src/andrei/andrei_main.cpp.s

src/game_core.o: src/game_core.cpp.o

.PHONY : src/game_core.o

# target to build an object file
src/game_core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_core.dir/build.make CMakeFiles/game_core.dir/src/game_core.cpp.o
.PHONY : src/game_core.cpp.o

src/game_core.i: src/game_core.cpp.i

.PHONY : src/game_core.i

# target to preprocess a source file
src/game_core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_core.dir/build.make CMakeFiles/game_core.dir/src/game_core.cpp.i
.PHONY : src/game_core.cpp.i

src/game_core.s: src/game_core.cpp.s

.PHONY : src/game_core.s

# target to generate assembly for a file
src/game_core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_core.dir/build.make CMakeFiles/game_core.dir/src/game_core.cpp.s
.PHONY : src/game_core.cpp.s

src/rend/cube_map.o: src/rend/cube_map.cpp.o

.PHONY : src/rend/cube_map.o

# target to build an object file
src/rend/cube_map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/rend/cube_map.cpp.o
.PHONY : src/rend/cube_map.cpp.o

src/rend/cube_map.i: src/rend/cube_map.cpp.i

.PHONY : src/rend/cube_map.i

# target to preprocess a source file
src/rend/cube_map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/rend/cube_map.cpp.i
.PHONY : src/rend/cube_map.cpp.i

src/rend/cube_map.s: src/rend/cube_map.cpp.s

.PHONY : src/rend/cube_map.s

# target to generate assembly for a file
src/rend/cube_map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/rend/cube_map.cpp.s
.PHONY : src/rend/cube_map.cpp.s

src/rend/objloader.o: src/rend/objloader.cpp.o

.PHONY : src/rend/objloader.o

# target to build an object file
src/rend/objloader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBJLoader.dir/build.make CMakeFiles/OBJLoader.dir/src/rend/objloader.cpp.o
.PHONY : src/rend/objloader.cpp.o

src/rend/objloader.i: src/rend/objloader.cpp.i

.PHONY : src/rend/objloader.i

# target to preprocess a source file
src/rend/objloader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBJLoader.dir/build.make CMakeFiles/OBJLoader.dir/src/rend/objloader.cpp.i
.PHONY : src/rend/objloader.cpp.i

src/rend/objloader.s: src/rend/objloader.cpp.s

.PHONY : src/rend/objloader.s

# target to generate assembly for a file
src/rend/objloader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBJLoader.dir/build.make CMakeFiles/OBJLoader.dir/src/rend/objloader.cpp.s
.PHONY : src/rend/objloader.cpp.s

src/rend/render.o: src/rend/render.cpp.o

.PHONY : src/rend/render.o

# target to build an object file
src/rend/render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/rend/render.cpp.o
.PHONY : src/rend/render.cpp.o

src/rend/render.i: src/rend/render.cpp.i

.PHONY : src/rend/render.i

# target to preprocess a source file
src/rend/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/rend/render.cpp.i
.PHONY : src/rend/render.cpp.i

src/rend/render.s: src/rend/render.cpp.s

.PHONY : src/rend/render.s

# target to generate assembly for a file
src/rend/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/src/rend/render.cpp.s
.PHONY : src/rend/render.cpp.s

src/rend/render_engine.o: src/rend/render_engine.cpp.o

.PHONY : src/rend/render_engine.o

# target to build an object file
src/rend/render_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/rend/render_engine.cpp.o
.PHONY : src/rend/render_engine.cpp.o

src/rend/render_engine.i: src/rend/render_engine.cpp.i

.PHONY : src/rend/render_engine.i

# target to preprocess a source file
src/rend/render_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/rend/render_engine.cpp.i
.PHONY : src/rend/render_engine.cpp.i

src/rend/render_engine.s: src/rend/render_engine.cpp.s

.PHONY : src/rend/render_engine.s

# target to generate assembly for a file
src/rend/render_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/rend/render_engine.cpp.s
.PHONY : src/rend/render_engine.cpp.s

src/serg/serg_main.o: src/serg/serg_main.cpp.o

.PHONY : src/serg/serg_main.o

# target to build an object file
src/serg/serg_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serg_libs.dir/build.make CMakeFiles/serg_libs.dir/src/serg/serg_main.cpp.o
.PHONY : src/serg/serg_main.cpp.o

src/serg/serg_main.i: src/serg/serg_main.cpp.i

.PHONY : src/serg/serg_main.i

# target to preprocess a source file
src/serg/serg_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serg_libs.dir/build.make CMakeFiles/serg_libs.dir/src/serg/serg_main.cpp.i
.PHONY : src/serg/serg_main.cpp.i

src/serg/serg_main.s: src/serg/serg_main.cpp.s

.PHONY : src/serg/serg_main.s

# target to generate assembly for a file
src/serg/serg_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serg_libs.dir/build.make CMakeFiles/serg_libs.dir/src/serg/serg_main.cpp.s
.PHONY : src/serg/serg_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... uninstall"
	@echo "... ANTTWEAKBAR_116_OGLCORE_GLFW"
	@echo "... BulletCollision"
	@echo "... BulletDynamics"
	@echo "... BulletSoftBody"
	@echo "... GLEW_1130"
	@echo "... LinearMath"
	@echo "... OBJLoader"
	@echo "... andrei_libs"
	@echo "... assimp"
	@echo "... game_core"
	@echo "... glfw"
	@echo "... mycontrol"
	@echo "... mydict"
	@echo "... mymatrix"
	@echo "... mynum"
	@echo "... render"
	@echo "... render_engine"
	@echo "... serg_libs"
	@echo "... zlib"
	@echo "... common/controls.o"
	@echo "... common/controls.i"
	@echo "... common/controls.s"
	@echo "... common/quaternion_utils.o"
	@echo "... common/quaternion_utils.i"
	@echo "... common/quaternion_utils.s"
	@echo "... common/shader.o"
	@echo "... common/shader.i"
	@echo "... common/shader.s"
	@echo "... common/texture.o"
	@echo "... common/texture.i"
	@echo "... common/texture.s"
	@echo "... common/vboindexer.o"
	@echo "... common/vboindexer.i"
	@echo "... common/vboindexer.s"
	@echo "... src/addlibs/MyControl.o"
	@echo "... src/addlibs/MyControl.i"
	@echo "... src/addlibs/MyControl.s"
	@echo "... src/addlibs/MyDict.o"
	@echo "... src/addlibs/MyDict.i"
	@echo "... src/addlibs/MyDict.s"
	@echo "... src/addlibs/MyNum.o"
	@echo "... src/addlibs/MyNum.i"
	@echo "... src/addlibs/MyNum.s"
	@echo "... src/addlibs/matrix.o"
	@echo "... src/addlibs/matrix.i"
	@echo "... src/addlibs/matrix.s"
	@echo "... src/andrei/andrei_main.o"
	@echo "... src/andrei/andrei_main.i"
	@echo "... src/andrei/andrei_main.s"
	@echo "... src/game_core.o"
	@echo "... src/game_core.i"
	@echo "... src/game_core.s"
	@echo "... src/rend/cube_map.o"
	@echo "... src/rend/cube_map.i"
	@echo "... src/rend/cube_map.s"
	@echo "... src/rend/objloader.o"
	@echo "... src/rend/objloader.i"
	@echo "... src/rend/objloader.s"
	@echo "... src/rend/render.o"
	@echo "... src/rend/render.i"
	@echo "... src/rend/render.s"
	@echo "... src/rend/render_engine.o"
	@echo "... src/rend/render_engine.i"
	@echo "... src/rend/render_engine.s"
	@echo "... src/serg/serg_main.o"
	@echo "... src/serg/serg_main.i"
	@echo "... src/serg/serg_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

